sudo: required
services:
  - docker

before_install:
  - docker build -t tchen90/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tchen90/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-028156859150"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  